ganado = ganado_ejemplo = [
    {"id": 1, "Marca": "M001", "Nacimiento": "2018-05-12", "Sexo": "Hembra", "Peso": 450, "Raza": "Holstein", "Estado_Salud": "Saludable", "Condicion_Corporal": "Adecuado", "Corral": 3},
    {"id": 2, "Marca": "M002", "Nacimiento": "2019-07-21", "Sexo": "Macho", "Peso": 480, "Raza": "Hereford", "Estado_Salud": "Enfermo", "Condicion_Corporal": "Bajo peso", "Corral": 2},
    {"id": 3, "Marca": "M003", "Nacimiento": "2020-03-15", "Sexo": "Hembra", "Peso": 470, "Raza": "Jersey", "Estado_Salud": "Saludable", "Condicion_Corporal": "Adecuado", "Corral": 1},
    {"id": 4, "Marca": "M004", "Nacimiento": "2017-09-30", "Sexo": "Macho", "Peso": 520, "Raza": "Angus", "Estado_Salud": "Herido", "Condicion_Corporal": "Adecuado", "Corral": 4},
    {"id": 5, "Marca": "M005", "Nacimiento": "2018-11-22", "Sexo": "Hembra", "Peso": 430, "Raza": "Simmental", "Estado_Salud": "Saludable", "Condicion_Corporal": "Sobrepeso", "Corral": 5},
    {"id": 6, "Marca": "M006", "Nacimiento": "2019-02-28", "Sexo": "Macho", "Peso": 500, "Raza": "Brahman", "Estado_Salud": "Enfermo", "Condicion_Corporal": "Bajo peso", "Corral": 3},
    {"id": 7, "Marca": "M007", "Nacimiento": "2020-06-17", "Sexo": "Hembra", "Peso": 455, "Raza": "Holstein", "Estado_Salud": "Saludable", "Condicion_Corporal": "Adecuado", "Corral": 2},
    {"id": 8, "Marca": "M008", "Nacimiento": "2018-10-10", "Sexo": "Macho", "Peso": 480, "Raza": "Hereford", "Estado_Salud": "Herido", "Condicion_Corporal": "Adecuado", "Corral": 1},
    {"id": 9, "Marca": "M009", "Nacimiento": "2017-12-05", "Sexo": "Hembra", "Peso": 460, "Raza": "Jersey", "Estado_Salud": "Saludable", "Condicion_Corporal": "Sobrepeso", "Corral": 4},
    {"id": 10, "Marca": "M010", "Nacimiento": "2020-01-13", "Sexo": "Macho", "Peso": 515, "Raza": "Angus", "Estado_Salud": "Enfermo", "Condicion_Corporal": "Bajo peso", "Corral": 5},
    {"id": 11, "Marca": "M011", "Nacimiento": "2019-04-18", "Sexo": "Hembra", "Peso": 445, "Raza": "Simmental", "Estado_Salud": "Saludable", "Condicion_Corporal": "Adecuado", "Corral": 3},
    {"id": 12, "Marca": "M012", "Nacimiento": "2020-08-27", "Sexo": "Macho", "Peso": 530, "Raza": "Brahman", "Estado_Salud": "Herido", "Condicion_Corporal": "Adecuado", "Corral": 2},
    {"id": 13, "Marca": "M013", "Nacimiento": "2018-06-06", "Sexo": "Hembra", "Peso": 435, "Raza": "Holstein", "Estado_Salud": "Saludable", "Condicion_Corporal": "Adecuado", "Corral": 1},
    {"id": 14, "Marca": "M014", "Nacimiento": "2019-11-01", "Sexo": "Macho", "Peso": 495, "Raza": "Hereford", "Estado_Salud": "Enfermo", "Condicion_Corporal": "Bajo peso", "Corral": 4},
    {"id": 15, "Marca": "M015", "Nacimiento": "2017-07-24", "Sexo": "Hembra", "Peso": 470, "Raza": "Jersey", "Estado_Salud": "Saludable", "Condicion_Corporal": "Sobrepeso", "Corral": 5},
    {"id": 16, "Marca": "M016", "Nacimiento": "2020-03-30", "Sexo": "Macho", "Peso": 525, "Raza": "Angus", "Estado_Salud": "Herido", "Condicion_Corporal": "Adecuado", "Corral": 3},
    {"id": 17, "Marca": "M017", "Nacimiento": "2018-09-18", "Sexo": "Hembra", "Peso": 440, "Raza": "Simmental", "Estado_Salud": "Saludable", "Condicion_Corporal": "Adecuado", "Corral": 2},
    {"id": 18, "Marca": "M018", "Nacimiento": "2019-02-14", "Sexo": "Macho", "Peso": 510, "Raza": "Brahman", "Estado_Salud": "Enfermo", "Condicion_Corporal": "Bajo peso", "Corral": 1},
    {"id": 19, "Marca": "M019", "Nacimiento": "2020-07-04", "Sexo": "Hembra", "Peso": 460, "Raza": "Holstein", "Estado_Salud": "Saludable", "Condicion_Corporal": "Adecuado", "Corral": 4},
    {"id": 20, "Marca": "M020", "Nacimiento": "2018-01-25", "Sexo": "Macho", "Peso": 500, "Raza": "Hereford", "Estado_Salud": "Herido", "Condicion_Corporal": "Adecuado", "Corral": 5},
    {"id": 21, "Marca": "M021", "Nacimiento": "2017-08-15", "Sexo": "Hembra", "Peso": 445, "Raza": "Jersey", "Estado_Salud": "Saludable", "Condicion_Corporal": "Adecuado", "Corral": 3},
    {"id": 22, "Marca": "M022", "Nacimiento": "2019-05-20", "Sexo": "Macho", "Peso": 470, "Raza": "Angus", "Estado_Salud": "Enfermo", "Condicion_Corporal": "Bajo peso", "Corral": 2},
    {"id": 23, "Marca": "M023", "Nacimiento": "2020-10-09", "Sexo": "Hembra", "Peso": 450, "Raza": "Simmental", "Estado_Salud": "Saludable", "Condicion_Corporal": "Adecuado", "Corral": 1},
    {"id": 24, "Marca": "M024", "Nacimiento": "2018-12-30", "Sexo": "Macho", "Peso": 480, "Raza": "Brahman", "Estado_Salud": "Herido", "Condicion_Corporal": "Adecuado", "Corral": 4},
    {"id": 25, "Marca": "M025", "Nacimiento": "2017-03-02", "Sexo": "Hembra", "Peso": 430, "Raza": "Holstein", "Estado_Salud": "Saludable", "Condicion_Corporal": "Sobrepeso", "Corral": 5},
    {"id": 26, "Marca": "M026", "Nacimiento": "2019-07-18", "Sexo": "Macho", "Peso": 500, "Raza": "Hereford", "Estado_Salud": "Enfermo", "Condicion_Corporal": "Bajo peso", "Corral": 3},
    {"id": 27, "Marca": "M027", "Nacimiento": "2020-06-24", "Sexo": "Hembra", "Peso": 470, "Raza": "Jersey", "Estado_Salud": "Saludable", "Condicion_Corporal": "Adecuado", "Corral": 2},
    {"id": 28, "Marca": "M028", "Nacimiento": "2018-04-07", "Sexo": "Macho", "Peso": 530, "Raza": "Angus", "Estado_Salud": "Herido", "Condicion_Corporal": "Adecuado", "Corral": 1},
    {"id": 29, "Marca": "M029", "Nacimiento": "2017-11-26", "Sexo": "Hembra", "Peso": 460, "Raza": "Simmental", "Estado_Salud": "Saludable", "Condicion_Corporal": "Sobrepeso", "Corral": 4},
    {"id": 30, "Marca": "M030", "Nacimiento": "2020-02-11", "Sexo": "Macho", "Peso": 515, "Raza": "Brahman", "Estado_Salud": "Enfermo", "Condicion_Corporal": "Bajo peso", "Corral": 5},
    {"id": 31, "Marca": "M031", "Nacimiento": "2018-07-22", "Sexo": "Hembra", "Peso": 435, "Raza": "Holstein", "Estado_Salud": "Saludable", "Condicion_Corporal": "Adecuado", "Corral": 3},
    {"id": 32, "Marca": "M032", "Nacimiento": "2019-09-13", "Sexo": "Macho", "Peso": 495, "Raza": "Hereford", "Estado_Salud": "Enfermo", "Condicion_Corporal": "Bajo peso", "Corral": 2},
    {"id": 33, "Marca": "M033", "Nacimiento": "2020-12-01", "Sexo": "Hembra", "Peso": 470, "Raza": "Jersey", "Estado_Salud": "Saludable", "Condicion_Corporal": "Adecuado", "Corral": 1},
    {"id": 34, "Marca": "M034", "Nacimiento": "2018-03-25", "Sexo": "Macho", "Peso": 520, "Raza": "Angus", "Estado_Salud": "Herido", "Condicion_Corporal": "Adecuado", "Corral": 4},
    {"id": 35, "Marca": "M035", "Nacimiento": "2017-06-15", "Sexo": "Hembra", "Peso": 450, "Raza": "Simmental", "Estado_Salud": "Saludable", "Condicion_Corporal": "Sobrepeso", "Corral": 5},
    {"id": 36, "Marca": "M036", "Nacimiento": "2019-05-27", "Sexo": "Macho", "Peso": 510, "Raza": "Brahman", "Estado_Salud": "Enfermo", "Condicion_Corporal": "Bajo peso", "Corral": 3},
    {"id": 37, "Marca": "M037", "Nacimiento": "2020-10-04", "Sexo": "Hembra", "Peso": 460, "Raza": "Holstein", "Estado_Salud": "Saludable", "Condicion_Corporal": "Adecuado", "Corral": 2},
    {"id": 38, "Marca": "M038", "Nacimiento": "2018-11-18", "Sexo": "Macho", "Peso": 500, "Raza": "Hereford", "Estado_Salud": "Herido", "Condicion_Corporal": "Adecuado", "Corral": 1},
    {"id": 39, "Marca": "M039", "Nacimiento": "2017-08-09", "Sexo": "Hembra", "Peso": 440, "Raza": "Jersey", "Estado_Salud": "Saludable", "Condicion_Corporal": "Sobrepeso", "Corral": 4},
    {"id": 40, "Marca": "M040", "Nacimiento": "2020-01-07", "Sexo": "Macho", "Peso": 525, "Raza": "Angus", "Estado_Salud": "Enfermo", "Condicion_Corporal": "Bajo peso", "Corral": 5},
    {"id": 41, "Marca": "M041", "Nacimiento": "2018-04-19", "Sexo": "Hembra", "Peso": 455, "Raza": "Simmental", "Estado_Salud": "Saludable", "Condicion_Corporal": "Adecuado", "Corral": 3},
    {"id": 42, "Marca": "M042", "Nacimiento": "2019-07-30", "Sexo": "Macho", "Peso": 475, "Raza": "Brahman", "Estado_Salud": "Herido", "Condicion_Corporal": "Adecuado", "Corral": 2},
    {"id": 43, "Marca": "M043", "Nacimiento": "2020-09-21", "Sexo": "Hembra", "Peso": 465, "Raza": "Holstein", "Estado_Salud": "Saludable", "Condicion_Corporal": "Adecuado", "Corral": 1},
    {"id": 44, "Marca": "M044", "Nacimiento": "2018-12-14", "Sexo": "Macho", "Peso": 485, "Raza": "Hereford", "Estado_Salud": "Herido", "Condicion_Corporal": "Adecuado", "Corral": 4},
    {"id": 45, "Marca": "M045", "Nacimiento": "2017-05-03", "Sexo": "Hembra", "Peso": 445, "Raza": "Jersey", "Estado_Salud": "Saludable", "Condicion_Corporal": "Adecuado", "Corral": 5},
    {"id": 46, "Marca": "M046", "Nacimiento": "2019-10-12", "Sexo": "Macho", "Peso": 495, "Raza": "Angus", "Estado_Salud": "Enfermo", "Condicion_Corporal": "Bajo peso", "Corral": 3},
    {"id": 47, "Marca": "M047", "Nacimiento": "2020-06-02", "Sexo": "Hembra", "Peso": 470, "Raza": "Simmental", "Estado_Salud": "Saludable", "Condicion_Corporal": "Adecuado", "Corral": 2},
    {"id": 48, "Marca": "M048", "Nacimiento": "2018-09-29", "Sexo": "Macho", "Peso": 530, "Raza": "Brahman", "Estado_Salud": "Herido", "Condicion_Corporal": "Adecuado", "Corral": 1},
    {"id": 49, "Marca": "M049", "Nacimiento": "2017-11-17", "Sexo": "Hembra", "Peso": 460, "Raza": "Holstein", "Estado_Salud": "Saludable", "Condicion_Corporal": "Sobrepeso", "Corral": 4},
    {"id": 50, "Marca": "M050", "Nacimiento": "2020-02-28", "Sexo": "Macho", "Peso": 515, "Raza": "Hereford", "Estado_Salud": "Enfermo", "Condicion_Corporal": "Bajo peso", "Corral": 5}
]


